### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ChinmayPatel** [yoshiori/pomodoro#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [pomodoro](https://github.com/yoshiori/pomodoro) package, v0.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /home/chinmay/.atom/packages/pomodoro/lib/pomodoro-view.coffee:5

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/chinmay/.atom/packages/pomodoro/lib/pomodoro-view.coffee:5:199)
  at /home/chinmay/.atom/packages/pomodoro/lib/pomodoro-view.coffee:5:3
  at Object.<anonymous> (/home/chinmay/.atom/packages/pomodoro/lib/pomodoro-view.coffee:46:5)
  at Object.<anonymous> (/home/chinmay/.atom/packages/pomodoro/lib/pomodoro-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/chinmay/.atom/packages/pomodoro/lib/pomodoro.coffee:3:16)
  at Object.<anonymous> (/home/chinmay/.atom/packages/pomodoro/lib/pomodoro.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /usr/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/usr/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -1:30.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  4x -1:28.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:25.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:25.7.0 settings-view:install-packages-and-themes (atom-text-editor.editor.vim-mode.command-mode)
  6x -1:20.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -1:10.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:07.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:07.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.mini.is-focused)
     -1:06.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:06.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:56.9.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.mini.is-focused)
     -0:56.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:56.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:53 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:36.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.4
browser-plus, v0.0.23
relative-line-numbers, v0.1.5
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by yoshiori** [comment]
fix 90a0a0898a3c41293e3f23a3b0f0cdf5acba436f
